# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build App Tier Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-appserver/Dockerfile'
        repository: 'yelb-appserver'
        tags: |
          $(tag)

    - task: prisma-cloud-compute-scan@3
      displayName: Scan App Tier Image
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-jp-demo'
        artifact: 'harbor.alson.space/cyberweek/yelb-appserver:v2.0'
        project: 'Cyberweek Project'

    - task: Docker@2
      displayName: Build Web Tier image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-ui/Dockerfile'
        tags: |
          $(tag)

    - task: prisma-cloud-compute-scan@3
      displayName: Scan UI Tier Image
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-jp-demo'
        artifact: 'harbor.alson.space/cyberweek/yelb-ui:v2.0'
        project: 'Cyberweek Project'

    - task: Docker@2
      displayName: Build DB Tier Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-db/Dockerfile'
        tags: |
          $(tag)
    - task: prisma-cloud-compute-scan@3
      displayName: Scan DB Tier Image
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-jp-demo'
        artifact: 'harbor.alson.space/cyberweek/yelb-db:v2.0'
        project: 'Cyberweek Project'
